# Generated by Django 3.2.12 on 2022-03-29 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='default',
            field=models.BooleanField(default=False, help_text='Indica se una bacheca è default o meno'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skill', related_query_name='user_skill', to='Core.skill'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skill', related_query_name='user_skill', to=settings.AUTH_USER_MODEL),
        ),
    ]
