# Generated by Django 3.2.7 on 2021-12-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type_skill',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Managment', 'Management'), ('Design', 'Design'), ('Other', 'Other')], default='Other', max_length=64, verbose_name='type skill'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('Base', 'Base'), ('Verified', 'Verified'), ('Innovator', 'Innovator')], default='Base', max_length=64, verbose_name='type user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_vip',
            field=models.CharField(choices=[('FREE', 'Free'), ('LV1', 'Lv1'), ('LV2', 'Lv2'), ('LV3', 'Lv3')], default='FREE', max_length=64, verbose_name='type vip'),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='type',
            field=models.CharField(choices=[('University', 'University'), ('Highschool', 'Highschool'), ('Master', 'Master'), ('Course', 'Course'), ('Doctorate', 'Doctorate'), ('Other', 'Other')], default='Other', max_length=32),
        ),
    ]
