# Generated by Django 3.2.7 on 2021-11-06 17:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='date_birth__gte',
        ),
        migrations.AlterField(
            model_name='user',
            name='project_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_by', related_query_name='saved_by', to='Core.Project'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_saved',
            field=models.ManyToManyField(blank=True, related_name='_Core_user_user_saved_+', related_query_name='saved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', related_query_name='skill', to='Core.skill'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_birth__gte', datetime.datetime(2021, 11, 6, 17, 53, 5, 289963, tzinfo=utc))), name='date_birth__gte'),
        ),
    ]
