# Generated by Django 3.2.7 on 2021-11-13 11:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProject',
            fields=[
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('text', models.TextField(help_text='Testo del modello', max_length=516, verbose_name='text')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('link_site', models.CharField(max_length=516)),
            ],
            options={
                'verbose_name': 'External Project',
                'verbose_name_plural': 'External Projects',
                'db_table': 'external_project',
            },
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('text', models.TextField(help_text='Testo del modello', max_length=516, verbose_name='text')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User Education',
                'verbose_name_plural': 'User Educations',
                'db_table': 'user_education',
            },
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='date_birth__gte',
        ),
        migrations.RemoveField(
            model_name='user',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='user',
            name='highscool',
        ),
        migrations.RemoveField(
            model_name='user',
            name='university',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='user',
            name='main_role',
            field=models.CharField(blank=True, help_text="Indica il ruolo principale dell'utente (32 caratteri max)", max_length=32, null=True, verbose_name='main role'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_site',
            field=models.TextField(blank=True, help_text='Link del sito di contatto del progetto', max_length=516, null=True, verbose_name='link site'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.TextField(blank=True, db_column='description', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('01', 'Base'), ('02', 'Verified'), ('03', 'Innovatore')], default='01', max_length=64, verbose_name='type user'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text="Livello di competenza della skill dell'utente", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='usereducation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', related_query_name='educations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalproject',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_projects', related_query_name='external_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
