# Generated by Django 3.2.7 on 2021-11-06 20:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20211106_1753'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='date_birth__gte',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_birth__gte', datetime.datetime(2021, 11, 6, 20, 55, 22, 727543, tzinfo=utc))), name='date_birth__gte'),
        ),
    ]
