# Generated by Django 3.2.7 on 2021-11-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20211113_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalproject',
            name='text',
        ),
        migrations.AddField(
            model_name='externalproject',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='externalproject',
            name='link_site',
            field=models.CharField(blank=True, max_length=516, null=True),
        ),
    ]
