# Generated by Django 3.2.12 on 2022-06-14 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_init_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='caption',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='posts_likes', related_query_name='posts_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
