# Generated by Django 3.2.12 on 2022-09-09 17:57

import Core.models.Community.TextPost
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20220614_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectanswer',
            old_name='answer',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='projectquestion',
            old_name='question',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='textpost',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=Core.models.Community.TextPost.file_path),
        ),
    ]
