# Generated by Django 3.2.7 on 2021-11-07 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20211106_2055'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='date_birth__gte',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_birth__gte', datetime.datetime(2021, 11, 7, 14, 4, 37, 910475, tzinfo=utc))), name='date_birth__gte'),
        ),
    ]
