# Generated by Django 3.2.7 on 2022-01-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20211229_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproject',
            options={'verbose_name': 'User Project', 'verbose_name_plural': 'User Projects'},
        ),
        migrations.RemoveIndex(
            model_name='userproject',
            name='user_projec_date_ad_00e3da_idx',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='date_added',
        ),
        migrations.AddField(
            model_name='userproject',
            name='created_at',
            field=models.DateTimeField(db_column='date_added', default=None, editable=False, help_text='Data di aggiunta utente nel progetto', null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='updated_at',
            field=models.DateTimeField(default=None, editable=False, help_text='Data di aggiornamento del modello', null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=None, editable=False, help_text='Data di creazione del modello', null=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(default=None, editable=False, help_text='Data di aggiornamento del modello', null=True, verbose_name='updated at'),
        ),
    ]
