# Generated by Django 3.2.7 on 2021-11-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20211113_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='type',
            field=models.CharField(choices=[('University', 'University'), ('Highschool', 'Highschool'), ('Master', 'Master'), ('Course', 'Course'), ('Doctorate', 'Doctorate'), ('Other', 'Other')], default='Other', max_length=32),
        ),
    ]
