# Generated by Django 3.2.7 on 2021-11-09 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20211107_1404'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='date_birth__gte',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('date_birth__gte', datetime.datetime(2021, 11, 9, 9, 57, 51, 807798, tzinfo=utc))), name='date_birth__gte'),
        ),
    ]
