# Generated by Django 3.2.7 on 2021-11-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_usereducation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='location'),
        ),
    ]
