# Generated by Django 3.2.7 on 2022-01-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_initial_showcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, db_column='secret_key', editable=False, null=True, unique=True, verbose_name='slug'),
        ),
    ]
