# Generated by Django 3.2.7 on 2021-11-20 10:23

import Core.models.Users.User
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(null=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Core.models.Users.User.image_path, verbose_name='image'),
        ),
    ]
